- README.md
- src/codegen.jl
- src/cxxmacro.jl
- src/initialization.jl
- src/typetranslation.jl
Updates intrinsic path for 3.7 and mentions that LLVM dev is targeting 3.7, see: https://github.com/Keno/Cxx.jl/issues/66
I also commented out a few `@show` calls that were showing up during loading.
> LLVM 3.7 Updates

- src/utils.jl
Use the `function Module.method` style rather than `import Module: method` since Cxx does not define a module.
> extend Base.dump

- src/initialization.jl
Though getting a new error now: 
```
Warning: error initializing module Cxx:
BoundsError(a=Array{Cxx.ClangCompiler, 1}[], i=(1,))
```
> Fix include path issue #34

- src/bootstrap.cpp
Perhaps a change to the LLVM API?  Maybe the wrong API?  This change assumes that [children()](http://clang.llvm.org/doxygen/classclang_1_1Stmt.html#a489148e5d234a5a7f00d8b02981bcee5) returns an [llvm::iterator_range](http://llvm.org/docs/doxygen/html/classllvm_1_1iterator__range.html).  Fixes #136.
> Use iterator_range semantics

- src/typetranslation.jl
Short and unsigned short are missing.
> Manage short and unsigned short types

- src/bootstrap.cpp
- src/clangwrapper.jl
- src/initialization.jl
- Fixed an issue where initialization.jl is not able to find gcc version on i686 ubuntu.
- Fixed assertion failure / segmentation fault issues in bootstrap.cpp and clangwrapper.jl
> fixes for ubuntu i686 issues.

- src/boot.h
Added stubs for gets and std::is_final in boot.h
> Workaround for old libstdc++

- deps/BuildBootstrap.Makefile
This change appears to be necessary to build Cxx.jl since this upstream change to lldb: https://github.com/llvm-mirror/lldb/commit/f5dcf4ff26adeb367781f731e3a9b0fffbc330a7
> Update BuildBootstrap.Makefile to work with latest lldb

- deps/BuildBootstrap.Makefile
- src/bootstrap.cpp
- src/initialization.jl
```
(lldb) expr jl_ExecutionEngine
(JuliaOJIT *) $0 = 0x0000000103063c00
(lldb) c
Process 14116 resuming
julia> versioninfo()
Julia Version 0.5.0-dev+2042
Commit 171b4ae* (2016-01-08 14:21 UTC)
Platform Info:
System: Darwin (x86_64-apple-darwin15.2.0)
CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
WORD_SIZE: 64
BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
LAPACK: libopenblas64_
LIBM: libopenlibm
LLVM: libLLVM-3.7.1
julia> Pkg.test("Cxx")
INFO: Testing Cxx
foo
foo
foo
foo
foo
foo
foo
foo
foo
foo
1
2
3
4
5
6
7
8
9
10
INFO: Cxx tests passed
```
> Fix build against llvm 3.7.1

- src/bootstrap.cpp
- src/typetranslation.jl
- test/misc.jl
I'm not really sure if this is the right fix but it did the job for the example I worked on, i.e. wrapping matrices from the Eigen library. For arbitrary size matrices they use `-1` as type parameter value so I got a `InexactError` when `specialize_template` tried to `convert` to a `UInt64`.
> Reinterpret (with unsigned) instead of converting to allow for negative type parameters

- src/codegen.jl
- test/misc.jl
Looks like #119 was actually two issues. This PR fixes the second one.
Before this PR, passing Int8, Int16, or UInt16 like so...
```
cxx""" void foo(unsigned short value) {} """
@cxx foo(UInt16(0))
```
would lead to
```
LoadError: Got bad type information while compiling Cxx.CppNNS{Tuple{:foo}} (got UInt16 for argument 1)
```
This PR adds the missing types in check_args using CxxBuiltinTypes.
> Use CxxBuiltinTypes in check_args. Fixes #119 (part 2)

- README.md
GCC >= 5 will not work.
ABI was adding cxx11 to method pointers which was incompatible with runtime resolution of Cxx (Clang).
See https://github.com/Keno/Cxx.jl/issues/223 for more info
> Added instruction to force clang to compile

- deps/BuildBootstrap.Makefile
- deps/build.jl
- src/Cxx.jl
- src/CxxREPL/replpane.jl
- src/initialization.jl
- test/llvmincludes.jl
Enable cases where julia binary and headers might be installed in different places.
The concrete case is the `jpata/ROOT.jl` package, where the julia binary resides in the Pkg directory and the `JULIA_HOME` variable points to that binary in order to be used to correctly launch any possible workers etc.
In such a case, building `Cxx.jl` fails.
Hence, `Cxx.jl` would benefit from an alternative way of configuring the julia header search paths. I propose to set it at build time via an environment variable, which would then be saved in a generated file.
> alternative julia install path

- src/initialization.jl
allow user to change the default root directory for loading the system
c++ libraries via the CXXJL_ROOTDIR environment variable as recommended
by keno in #245
> Control default system rootdir

- src/codegen.jl
- src/cxxtypes.jl
This comment is outdated and a bit confusing because `CppValues` are now stack allocated.
> remove outdated comment

- src/bootstrap.cpp
- src/initialization.jl
This is the minimal change necessary to freely choose target triple and cpu.
`CI = Cxx.new_clang_instance(false, false, target = "nvptx64-nvidia-cuda", CPU = "sm_35")`
I am running into the problem that I need to set specific options to TargetOpts and and CodeGenOpts.
> Allow for Triple and CPU to be set per compiler instance

- src/bootstrap.cpp
```julia
CI = Cxx.new_clang_instance(false, false, target = "nvptx64-nvidia-c    uda", CPU = "sm_35")
addHeaderDir(CI, "/opt/cuda/include", kind = C_System)
cxxinclude(CI, "__clang_cuda_runtime_wrapper.h")
```
I think I still miss some options, but this gets me 95% of the way.
> [RFC] Configure Cuda options if targets starts with nvptx

- src/bootstrap.cpp
When we are compiling for a CUDA device we need to set the CUDAIsDevice attr to functions (and maybe some other places, but this is the minimal change that got my example working)
> set the __device__ attribute to functions

- src/clangwrapper.jl
when embedding a `Val{n}` as a constant expression. Not sure why the LLVM assertion happens only on REPL for me, not in Pkg.test("Cxx"), but the change does fix the issue.
```
julia> cxx"""
template <int i> class Template246 {
public:
int getI() { return i; }
};
"""
true
julia> icxx"Template246<$(Val{5})>().getI();" == 5
Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file /Users/ryuyamamoto/julia/deps/srccache/llvm-3.7.1/include/llvm/Support/Casting.h, line 237.
signal (4): Illegal instruction: 4
while loading no file, in expression starting on line 0
abort at /Users/ryuyamamoto/julia/usr/lib//libLLVM-3.7.dylib (unknown line)
__assert_rtn at /Users/ryuyamamoto/julia/usr/lib//libLLVM-3.7.dylib (unknown line) …
```
> Fix typo in clangwrapper.jl that triggers an LLVM assersion

- src/exceptions.jl
This also fixes the deprecation warning on v0.5
Now that tests are passing locally both on v0.5 and v0.6 without deprecation warnings.
> Fix show error on v0.6: use `unsafe_string` instead of `bytestring`

- src/bootstrap.cpp
RTTI defaults to off, as before, but can now be switched on at any time (before `using Cxx.jl`) via
export JULIA_CXX_RTTI=1
*without* rebuilding Cxx.jl 
Addresses #166. It guess it's not full solution (keep #166 open?) - but until one is found, it should make life a lot easier for people who need RTTI (like @jpata and myself). :-)
This includes #311.
> Use environment variable JULIA_CXX_RTTI to switch RTTI on or off

- .gitignore
- .travis.yml
- README.md
- codecov.yml
This PR adds status badges for ~~PkgEval,~~ Travis, and ~~Coveralls~~ Codecov to the README and sets up Travis to submit coverage info. ~~Note that you'll have to manually enable the Coveralls service for this repo at https://coveralls.io.~~ I've also added the standard gitignore file that ignores coverage-related files.
> Add badges to README, submit coverage

- src/initialization.jl
Rely on `xcrun` and `xcode-select` commands instead of `xcodebuild` (available only with a complete Xcode installation) and hardcoding paths. Now C++ headers are found even only with the Apple Command Line Tools installed, see issue #363. Changes should be propagated to all the other tags. Credits to @EmileParolin for suggesting `xcrun`.
> Improvements in looking for C++ headers on apple systems

- src/initialization.jl
Adding an additional triple. The path on Clear Linux version 29310 to the gcc libraries is `/usr/lib64/gcc/x86_64-generic-linux/9/`.
Note that while I can build Cxx, I don't have it working yet locally. However, I imagine this PR should be fine.
```julia
julia> using Cxx
[ Info: Recompiling stale cache file /home/chriselrod/.julia/compiled/v1.2/Cxx/ESGkI.ji for Cxx [a0b5b9ef-44b7-5148-a2d1-f6db19f3c3d2]
signal (11): Segmentation fault
in expression starting at REPL[2]:1
_ZN4llvm11InstructionC2EPNS_4TypeEjPNS_3UseEjPS0_ at /home/chriselrod/Documents/languages/julia6/usr/bin/../lib/libLLVM-6.0.so (unknown line)
_ZN4llvm10AllocaInstC1EPNS_4TypeEjPNS_5ValueERKNS_5TwineEPNS_11InstructionE at /home/chriselrod/Documents/languages/julia6/usr/bin/../lib/libLLVM-6.0.so (unknown line) …
```
> Added x86_64-generic-linux tripple, used by Clear Linux.

- src/initialization.jl
`/usr/include` is missing on mojave+, it's suggested to use `SDKs/MacOSX.sdk/usr/include`.
> Fix macOS sdk path

- src/initialization.jl
Using `xcrun` instead of `xcode-select` will give us the proper paths.
I haven't tested this patch against older versions of macOS. It looks like it should work on Mojave ([https://apple.stackexchange.com/questions/337940/why-is-usr-include-missing-i-have-xcode-and-command-line-tools-installed-moja](https://apple.stackexchange.com/questions/337940/why-is-usr-include-missing-i-have-xcode-and-command-line-tools-installed-moja)).
This should fix #442.
> Fix headers not being found on macOS Catalina.

- src/bootstrap.cpp
Hello! Persuant to @vchuravy's suggestion in [Julia PR #31272](https://github.com/JuliaLang/julia/pull/31272), I'd like to restore some commented-out code that makes all globals external. My proposed changes in the Julia PR tweak `llvmcall` to no longer silently discard non-external linkage for globals. However, as it turns out, Cxx.jl seems to implicitly rely on `llvmcall` discarding non-external linkage. Hence this PR.
I used `Pkg.test()` to run Cxx.jl's tests. With my proposed changes, Cxx.jl's tests all pass when run on my machine using the modified version of Julia from my aforementioned PR. Cxx.jl's tests also pass when run using Julia compiled from the master branch (hopefully the CI builds will confirm that). Is there anything else I should do to test if Cxx.jl still works?
> Make globals external again

- src/initialization.jl
Using Cxx on a system like Gentoo or some supercomputers with multiple
compilers installed in non-standard locations will result in Cxx not finding
the standard library.  This change allows users to specify where to find 
the system includes in a way that doesn't requiring forking Cxx to make
these changes.  Since these systems are inherently non-standard, these 
changes are unlikely to be fixed with a change to `CollectLinuxHeaderPaths!` 
so providing anoverride is better.
This patch is an updated version of pull request #324 and #283 which no longer
compile with the current version of Cxx.  It also serves as a solution to the issue 
raised #315 that doesn't require a solution like VPetukhov suggested which 
essentially forks Cxx for every user with these nonstandard locations.
> Provide override for standard headers in C++

- src/initialization.jl
See https://github.com/JuliaInterop/Cxx.jl/pull/448#issuecomment-569572573; the order of `headers` appears to make a difference (at least on my machine):
```julia
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
OS: Linux (x86_64-linux-gnu)
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```
> Move user override for standard headers to take precedence over all others

- README.md
I have decided to create this pull request to notify unaware users that they need a specific Julia version to install Cxx.jl.
> Works with Julia 1.3 or older

- Project.toml
Due to issues with Julia 1.4, use tilde operator to state compatibility with Julia [1.3.0, 1.4.0) since this is not operational on 1.4
> Update Project.toml for compat 1.3 and not 1.4
